### ISSUE TITLE
mulitple scripts running simulatenously?

### ISSUE THREAD

**Issue by TaterCode** [pimoroni/pibrella#16]
Hi there,
is it possible to have more than one script accessing the pibrella at a time?
I'm using the traffic light to tell me which wifi network my pi is connected to. That I would always like running in the background.
But I'd like to access the pibrella with another script to change the IO state of the other lines as well at some point.
But i'm finding that if I set the green LED on in script #1,
Later when script #2 runs, the light goes off (I'm not doing anything with the led's in that one).
I guess that the pibrella is resetting each time a new script is run.
Thanks!

**Comment by Gadgetoid** [comment]
Yes, the Pibrella will be resetting into its default state every time the library is loaded, which happens when the script is run. You could use RPi.GPIO to directly control the LEDs, rather than using the Pibrella library. If you know what you're doing, then the library is a lot of bloat which you might not need.

**Comment by TaterCode** [comment]
Hi Philip,
Thanks, I'll check it out.
Actually so far whatever bloat there is is far outweighed by the
convinience of the Pibrella. It's an easy addition to all of my projects
and "just works." Can't beat it!
- Matt

On Saturday, September 5, 2015, Philip Howard <notifications@github.com>
wrote:

> Yes, the Pibrella will be resetting into its default state every time the
> library is loaded, which happens when the script is run. You could use
> RPi.GPIO to directly control the LEDs, rather than using the Pibrella
> library. If you know what you're doing, then the library is a lot of bloat
> which you might not need.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pimoroni/pibrella/issues/16#issuecomment-137982845>.
>


-- 
- Matt

Matthew Breit
matt.breit@gmail.com
Sent from MetroMail
