### ISSUE TITLE
Buzzer is muted after several melodie(s) executions

### ISSUE THREAD

**Issue by absolument** [pimoroni/pibrella#18]
When I play several times a melody (with pibrella.buzzer.melody), after a certain number of times, or notes, the buzzer dont emits any sounds, without Python returns an error.
I have to quit and restart Python, before the buzzer is functional again (but the problem is not solved).

Here is a test code :

```
import pibrella, time

count = 0
def r2(pin=None):
        """Inspired by R2D2"""
        global count
        count +=1
        #melody(
        #   notes count : 199
        #   duration=0.0045
        #   loop=False
        # )
        pibrella.buzzer.melody(['N',1568,1568,1568,1568,1568,1568,1568,1568,1568,0,0,0,0,0,0,0,0,0,2864.0,2364.5,2198.0,2114.75,2064.8,2031.5,2007.71,1989.88,1976.0,0,0,0,0,0,0,0,0,0,2155.0,2155.0,2155.0,2155.0,2155.0,2155.0,2155.0,2155.0,2155.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1976,1976,1976,1976,1976,1976,1976,1976,1976,0,0,0,0,0,0,0,0,0,3704.0,2732.0,2408.0,2246.0,2148.8,2084.0,2037.71,2003.0,1976.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2552.0,2106.5,1958.0,1883.75,1839.2,1809.5,1788.29,1772.38,1760.0,0,0,0,0,0,0,0,0,0,3405.0,2811.0,2613.0,2514.0,2454.6,2415.0,2386.71,2365.5,2349.0,0,0,0,0,0,0,0,0,0,2489,2489,2489,2489,2489,2489,2489,2637,2637,2637,2637,2637,2637,2637,2637,2637,2637,2637,2637,2637,2489,2489,2489,2489,2489,2489,2093,2093,2093,2093,2093,2093,2093,1976,1976,1976,1976],.0045,0)
        print(count)

def loop(n=1):
        for x in range(n):
                r2()
                time.sleep(1)
```

_Tested on Raspberry Pi 2, Python 3.4 in command line_
On 35 loop, the buzzer stop after few notes on the 32th execution, but the loop still running

_I had the same kind of problems before, using Python 2.7, other methods of buzzer (note, buzz, pwm), or using a decimal notation (list as argument for buzzer.melody)_

_The 'loop' parameter of buzzer.melody is not an option. The problem is the same with different melodies, random melodies, or procedural melodies (based on functions or list generator). I even feel that it is worse..._
_It seems that the number of notes you can play is limited. And I suspect it may have the same problem on other outputs (e,f,g,h, outputs and lights)_

**Comment by absolument** [comment]
After a test on a Piezo pluged on H output and played via pibrella.output.h.pwm()
It's the same : sounds stop at the 32th execution (around 6400 notes were played)
So, the problem may comes from Output class, not specific to Buzzer.

Here is my test code :
```
import pibrella, time

count = 0
sfx = pibrella.output.h

def melody(notes, duration):
        global sfx
        for f in notes:
                if f > 0: sfx.pwm(f,30)
                else: sfx.off()
                time.sleep(duration)
        sfx.off()

def r2(pin=None):
        global count
        count += 1
        melody([1568,1568,1568,1568,1568,1568,1568,1568,1568,0,0,0,0,0,0,0,0,0,2864.0,2364.5,2198.0,2114.75,2064.8,2031.5,2007.71,1989.88,1976.0,0,0,0,0,0,0,0,0,0,2155.0,2155.0,2155.0,2155.0,2155.0,2155.0,2155.0,2155.0,2155.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1976,1976,1976,1976,1976,1976,1976,1976,1976,0,0,0,0,0,0,0,0,0,3704.0,2732.0,2408.0,2246.0,2148.8,2084.0,2037.71,2003.0,1976.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2552.0,2106.5,1958.0,1883.75,1839.2,1809.5,1788.29,1772.38,1760.0,0,0,0,0,0,0,0,0,0,3405.0,2811.0,2613.0,2514.0,2454.6,2415.0,2386.71,2365.5,2349.0,0,0,0,0,0,0,0,0,0,2489,2489,2489,2489,2489,2489,2489,2637,2637,2637,2637,2637,2637,2637,2637,2637,2637,2637,2637,2637,2489,2489,2489,2489,2489,2489,2093,2093,2093,2093,2093,2093,2093,1976,1976,1976,1976],0.0045)
        print(count)

def loop(n=1):
        for x in range(n):
                r2()
                time.sleep(1)
```

**Comment by Gadgetoid** [comment]
I have a suspicion that it's a problem buried much deeper in the software stack, so it'll warrant some investigation. At the moment Pibrella isn't my highest priority, but I don't want to leave it neglected!
